apiVersion: authorization.openshift.io/v1
kind: ClusterRoleBinding
metadata:
  name: spark-default-sa-nemo
roleRef:
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: spark