apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-shuffle
  labels:
    app: spark-shuffle
    version: spark-2.4.3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-shuffle
  template:
    metadata:
      labels:
        app: spark-shuffle
        version: spark-2.4.3
    spec:
      containers:
      - name: spark-shuffle
        image: "docker.io/dimssss/spark-shuffle:v2.4.3"
        imagePullPolicy: Always
        ports:
        - containerPort: 7337